docs/src/content/docs/guides/youtube.mdx, src/config/mod.rs, src/main.rs, src/ui/mod.rs
currently used only for youtube download
prevents the main thread from blocking
=> feat: introduce worker queue

.github/workflows/ci.yml, src/config/keys/mod.rs, src/config/mod.rs
Tests were failing in release mode due to missing debug assertions for log screen related stuff
Also added release mode tests to CI
=> fix: release mode tests compilation issues

docs/src/content/docs/guides/installation.mdx, docs/src/content/docs/guides/try.mdx
Added in https://github.com/NixOS/nixpkgs/pull/330527
=> docs: add nix to install methods

assets/example_theme.ron, src/config/theme/properties.rs, src/ui/screens/mod.rs
fixes https://github.com/mierak/rmpc/issues/38
=> fix: Fix filename property behavior

docs/src/content/docs/installation.mdx
Fixes https://github.com/mierak/rmpc/issues/69
=> docs: add tumbleweed to install methods

CHANGELOG.md, src/logging.rs, src/main.rs, src/ytdlp.rs
fixes https://github.com/mierak/rmpc/issues/74
=> fix: logging in CLI mode, cleanup after yt-dlp fails

CHANGELOG.md, src/ui/browser.rs, src/ui/panes/queue.rs, src/ui/panes/search.rs, src/ui/utils/dirstack/dir.rs
=> feat: incremental search

CHANGELOG.md, src/config/mod.rs, src/main.rs, src/tmux.rs, src/ui/image/iterm2.rs, src/ui/image/kitty.rs, src/ui/image/sixel.rs, src/ui/image/ueberzug.rs, src/utils.rs
fixes https://github.com/mierak/rmpc/issues/93
=> fix: ueberzugpp redraw when not visible in tmux

src/ui/mod.rs
Basically, title. Useful when "studying" a song that lead to paused it
frequently. Works with mouse too.
=> feat: allow to seek backward/forward while paused

CHANGELOG.md, src/ui/mod.rs, src/ui/panes/albums.rs, src/ui/panes/artists.rs, src/ui/panes/directories.rs, src/ui/panes/playlists.rs, src/ui/panes/playlists/tests.rs
Finishes https://github.com/mierak/rmpc/issues/116
=> fix: browser panes remember cursor position in root level

CHANGELOG.md, assets/example_config.ron, docs/src/content/docs/configuration/keybinds.mdx, src/cli.rs, src/config/cli.rs, src/config/keys/actions.rs, src/config/keys/mod.rs, src/mpd/commands/decoders.rs, src/mpd/commands/mod.rs, src/mpd/mpd_client.rs, src/tests/fixtures/mpd_client.rs, src/ui/mod.rs, src/ui/modals/decoders.rs, src/ui/modals/mod.rs
For the modal I chose the keybind `P` (mnemonic for `P`lugins) but I don't know if it deserves a default binding as it is purely informational. Tell me what do you think.
CLI
```sh
$ rmpc decoders
[{"name":"mad","suffixes":["mp2","mp3"],"mime_types":["audio/mpeg"]},{"name":"mpg123","suffixes":["mp3"],"mime_types":[]},{"name":"vorbis","suffixes":["oga","ogg"],"mime_types":["application/ogg","application/x-ogg","audio/ogg","audio/vorbis","audio/vorbis+ogg","audio/x-ogg","audio/x-vorbis","audio/x-vorbis+ogg"]},{"name":"oggflac","suffixes":["oga","ogg"],"mime_types":["application/ogg","application/x-ogg","audio/ogg","audio/x-flac+ogg","audio/x-ogg"]},{"name":"flac","suffixes":["flac"],"mime_types":["application/flac","application/x-flac","audio/flac","audio/x-flac"]},{"name":"opus","suffixes": …
```
=> feat: list MPD decoder plugins (modal/cli)

CHANGELOG.md, src/shared/ext.rs, src/ui/modals/decoders.rs, src/ui/modals/song_info.rs
Not the ideal solution as this effectively makes a single table row into multiple ones, but should not matter for this use case.
=> fix: weird rendering and click to select in modal tables with wrapped lines

CHANGELOG.md, docs/src/content/docs/configuration/keybinds.mdx, src/config/cli.rs, src/config/keys/actions.rs, src/mpd/mpd_client.rs, src/shared/ext.rs, src/tests/fixtures/mpd_client.rs, src/ui/browser.rs, src/ui/panes/albums.rs, src/ui/panes/artists.rs, src/ui/panes/directories.rs, src/ui/panes/playlists.rs, src/ui/panes/search.rs
fixes https://github.com/mierak/rmpc/issues/133
=> feat: open or play action

CHANGELOG.md, src/context.rs, src/main.rs, src/ui/mod.rs, src/ui/panes/album_art.rs, src/ui/panes/queue.rs, src/ui/widgets/header.rs
fixes https://github.com/mierak/rmpc/issues/146
=> fix: album art not clearing when stopped

docs/src/content/docs/try-without-install.mdx
This commit is intended to be reverted in, I think, about ~3-4 months from 24.11's release, that should be enough time for everyone to make the switch. This PR is for the people that are/will still be on 24.05.
=> Add a (temporary) try on NixOS 24.05 instruction in the docs.

CHANGELOG.md, src/mpd/mpd_client.rs, src/ui/panes/queue.rs
fixes https://github.com/mierak/rmpc/issues/155
=> feat: select and move multiple songs in queue

docs/src/content/docs/try-without-install.mdx
fixes https://github.com/mierak/rmpc/issues/162
=> docs: mention mpd prerequisite

CHANGELOG.md, assets/example_config.ron, docs/src/content/docs/configuration/index.mdx, src/config/artists.rs, src/config/mod.rs, src/ui/browser.rs, src/ui/panes/albums.rs, src/ui/panes/artists.rs, src/ui/panes/directories.rs, src/ui/panes/mod.rs, src/ui/panes/playlists.rs
fixes https://github.com/mierak/rmpc/issues/147
=> feat: show album date in (album)artists panes

src/ui/panes/artists.rs
fixes issues from https://github.com/mierak/rmpc/pull/173
=> fix: add song/album to queue and cmd env in artists

src/ui/panes/lyrics.rs
fixes https://github.com/mierak/rmpc/issues/175
=> fix: lyrics being off by one line

CHANGELOG.md, src/core/event_loop.rs, src/shared/ext.rs, src/ui/mod.rs, src/ui/panes/mod.rs, src/ui/panes/playlists/tests.rs, src/ui/panes/queue.rs, src/ui/tab_screen.rs
fixes https://github.com/mierak/rmpc/issues/178
=> feat: apply scrollof in queue on start

src/ui/tab_screen.rs
fixes issues from https://github.com/mierak/rmpc/pull/180
=> fixup: full border on splits being broken

CHANGELOG.md, src/ui/mod.rs
fixes https://github.com/mierak/rmpc/issues/185
=> fix: ToggleSingle and ToggleConsume causing playback to stop

CHANGELOG.md, src/shared/lrc/lyrics.rs
fixes https://github.com/mierak/rmpc/issues/199
=> feat: support repeating lyrics

CHANGELOG.md, docs/src/content/docs/next/configuration/tabs.mdx, src/config/tabs.rs, src/config/theme/queue_table.rs, src/shared/ext.rs, src/shared/geometry.rs, src/ui/mod.rs, src/ui/panes/queue.rs, src/ui/tab_screen.rs
Allows for fixed pane size, same as columns in the queue table. This will allow to for example specify exact number of rows in the lyrics pane.
=> feat: fixed size pane

.github/workflows/relase.yml
fixes https://github.com/mierak/rmpc/issues/187
=> cicd: add macos binary to release

CHANGELOG.md, docs/src/content/docs/next/configuration/header.mdx, docs/src/content/docs/next/configuration/song-table.mdx, docs/src/content/docs/next/guides/on_song_change.mdx, src/config/cli.rs, src/config/theme/properties.rs, src/config/theme/queue_table.rs, src/context.rs, src/core/client.rs, src/core/command.rs, src/core/event_loop.rs, src/main.rs, src/mpd/commands/current_song.rs, src/mpd/commands/mod.rs, src/mpd/commands/stickers.rs, src/mpd/mpd_client.rs, src/mpd/proto_client.rs, src/tests/fixtures/mod.rs, src/tests/fixtures/mpd_client.rs, src/ui/panes/artists.rs, src/ui/panes/mod.rs, src/ui/panes/playlists/tests.rs
addresses https://github.com/mierak/rmpc/issues/210
=> [WIP] feat: sticker support

CHANGELOG.md, src/ui/panes/playlists.rs
addresses issue rised in https://github.com/mierak/rmpc/issues/212
=> feat: support preview in playlists for songs outside of the music db

CHANGELOG.md, Cargo.toml, docs/src/content/docs/next/guides/on_song_change.mdx, docs/src/content/docs/next/reference/cli-command-mode.mdx, src/config/cli.rs, src/context.rs, src/core/command.rs, src/core/event_loop.rs, src/core/mod.rs, src/core/socket.rs, src/core/work.rs, src/main.rs, src/shared/events.rs, src/shared/logging.rs, src/shared/lrc/index.rs, src/shared/lrc/mod.rs, src/shared/macros.rs, src/shared/mod.rs, src/shared/socket.rs, src/ui/mod.rs
This PR introduces remote communication to rmpc which allows scripts and cli to interact with running rmpc instance via unix socket. This can currently be used to display notification messages in rmpc from scripts and to notify rmpc about lyrics being downloaded.
The remote communication protocol, while extremely simplistic, is "private" and not documented by design so we can change it in the future if we need to, it is instead wrapped inside rmpc's CLI.
Fixes https://github.com/mierak/rmpc/issues/230
=> [WIP] feat: auto fetch lrc

CHANGELOG.md, src/config/cli.rs, src/core/event_loop.rs, src/shared/events.rs, src/shared/socket.rs, src/shared/tmux.rs, src/ui/image/ueberzug.rs, src/ui/mod.rs, src/ui/panes/album_art.rs
fixes https://github.com/mierak/rmpc/issues/252
=> fix: album art not updating when not active in tmux

CHANGELOG.md, Cargo.lock, Cargo.toml, docs/src/content/docs/next/assets/example_config.ron, docs/src/content/docs/next/configuration/index.mdx, docs/src/content/docs/next/configuration/song-table.mdx, src/config/defaults.rs, src/config/mod.rs, src/config/theme/properties.rs, src/config/theme/queue_table.rs, src/ui/panes/albums.rs, src/ui/panes/directories.rs, src/ui/panes/mod.rs, src/ui/panes/tag_browser.rs
fixes https://github.com/mierak/rmpc/issues/290
=> feat: configurable song sorting

src/config/cli.rs, src/main.rs
fixes https://github.com/mierak/rmpc/issues/293
sadly by removing the config path altogether since I have not found another way to make them consistent
=> fix: inconsistent default config path in cli/man

CHANGELOG.md, src/mpd/proto_client.rs, src/shared/string_util.rs
fixes https://github.com/mierak/rmpc/issues/301
=> fix: handle invalid utf8 characters

CHANGELOG.md, Cargo.lock, Cargo.toml, docs/src/content/docs/next/assets/example_config.ron, docs/src/content/docs/next/configuration/keybinds.mdx, src/config/cli.rs, src/config/keys/actions.rs, src/config/keys/mod.rs, src/core/command.rs, src/mpd/commands/lsinfo.rs, src/mpd/mpd_client.rs, src/tests/fixtures/mpd_client.rs, src/ui/mod.rs, src/ui/modals/add_random_modal.rs, src/ui/modals/confirm_modal.rs, src/ui/modals/info_modal.rs, src/ui/modals/input_modal.rs, src/ui/modals/mod.rs, src/ui/modals/select_modal.rs
fixes https://github.com/mierak/rmpc/issues/312
=> feat: addrandom command

CHANGELOG.md, docs/src/content/docs/next/guides/youtube.mdx, src/config/cli_config.rs, src/config/mod.rs, src/shared/ytdlp.rs
fixes https://github.com/mierak/rmpc/issues/320
=> feat: soundcloud support

CHANGELOG.md, docs/src/content/docs/next/configuration/keybinds.mdx, src/config/keys/actions.rs, src/ui/browser.rs, src/ui/panes/queue.rs, src/ui/panes/search.rs
=> feat: add and replace songs to queue

CHANGELOG.md, docs/src/content/docs/next/assets/example_config.ron, docs/src/content/docs/next/configuration/keybinds.mdx, src/config/keys/actions.rs, src/config/keys/mod.rs, src/mpd/mpd_client.rs, src/tests/fixtures/mpd_client.rs, src/ui/panes/queue.rs
=> feat: shuffle queue

CHANGELOG.md, docs/src/content/docs/next/configuration/index.mdx, src/config/mod.rs, src/ui/dirstack/state.rs, src/ui/panes/queue.rs
finishes https://github.com/mierak/rmpc/issues/338
=> feat: add center_current_song_on_change

CHANGELOG.md, docs/src/content/docs/next/configuration/header.mdx, src/config/theme/properties.rs, src/context.rs, src/tests/fixtures/mod.rs, src/ui/mod.rs, src/ui/panes/mod.rs
=> feat: active tab property

CHANGELOG.md, docs/src/content/docs/next/configuration/theme.mdx, src/config/defaults.rs, src/config/theme/mod.rs, src/shared/ext.rs, src/ui/mod.rs, src/ui/modals/decoders.rs, src/ui/modals/keybinds.rs, src/ui/modals/outputs.rs, src/ui/modals/select_modal.rs, src/ui/modals/song_info.rs, src/ui/panes/logs.rs, src/ui/panes/queue.rs, src/ui/panes/search.rs, src/ui/widgets/browser.rs
Fixes #337
Hopefully this does not break anything, working with the scrollbars is kinda icky due to some... less than optimal decisions in the past.
=> feat: allow disabling scrollbars

CHANGELOG.md, src/ui/modals/keybinds.rs
Idk at least the items don't get shuffled randomly with each initialization. Also, I noticed a typo in the chain.
=> Feat: sort keybinds in the help modal

CHANGELOG.md, src/ui/panes/queue.rs
=> fix: filter overlapping queue table without header

CHANGELOG.md, docs/src/content/docs/next/configuration/keybinds.mdx, src/core/command.rs, src/core/event_loop.rs
=> feat: include song metadata in externalcommand

CHANGELOG.md, src/config/keys/actions.rs, src/config/keys/mod.rs, src/ui/modals/keybinds.rs
fixes https://github.com/mierak/rmpc/issues/369
=> feat: sort keybinds by enum order

CHANGELOG.md, docs/src/content/docs/next/assets/example_theme.ron, docs/src/content/docs/next/configuration/theme.mdx, src/config/defaults.rs, src/config/theme/level_styles.rs, src/config/theme/mod.rs, src/ui/mod.rs, src/ui/panes/progress_bar.rs
=> feat: add level_styles to config statusbar styles

CHANGELOG.md, docs/src/content/docs/next/assets/example_config.ron, docs/src/content/docs/next/assets/example_theme.ron, docs/src/content/docs/next/configuration/index.mdx, src/config/mod.rs, src/ui/mod.rs
=> feat: rewind to start for tui

CHANGELOG.md, docs/src/content/docs/next/assets/example_config.ron, docs/src/content/docs/next/configuration/index.mdx, src/config/mod.rs, src/core/event_loop.rs, src/mpd/commands/status.rs, src/shared/mpd_query.rs
Please do read the documentation carefully if you do decide to use this.
Closes #371
=> feat: reflect changes to playlist

CHANGELOG.md, src/config/theme/progress_bar.rs
- Added a test for 3 symbol Progress Bar
- Will help avoid errors in future when changing progress bar code
- None
=> Added 3 Symbol Progress Bar Test

docs/src/content/docs/next/configuration/cava.mdx, src/config/cava.rs, src/config/defaults.rs, src/config/mod.rs, src/config/sort_mode.rs, src/config/theme/mod.rs, src/ui/panes/cava.rs
=> fix: quick cava fixes and a bit of refactor

src/config/mod.rs, src/core/client.rs, src/mpd/proto_client.rs
=> fix: attempt to fix connection getting stuck

CHANGELOG.md, docs/src/content/docs/next/guides/youtube.mdx, src/shared/ytdlp.rs
=> feat: suport niconico

docs/src/content/docs/next/configuration/cava.mdx
=> docs: fix cava symbols

docs/src/content/docs/next/configuration/cava.mdx, src/config/cava.rs
https://github.com/mierak/rmpc/issues/440
=> change cava default noise reduction to reflect cava

src/config/cli.rs, src/context.rs, src/core/event_loop.rs, src/shared/events.rs, src/shared/ipc/commands/mod.rs, src/shared/ipc/commands/status_message.rs, src/shared/logging.rs, src/shared/mod.rs, src/shared/ring_vec.rs, src/tests/fixtures/mod.rs, src/ui/mod.rs, src/ui/panes/logs.rs, src/ui/panes/progress_bar.rs
Adds timeout to remote status command. Also store the status messages for future use.
=> feat: remote status timeout

.github/workflows/ci.yml, .typos.toml
setting up [typos](https://github.com/marketplace/actions/typos-action) with configuration to avoid false positive
#454 
- ~~Documentation has been updated (if needed)~~
- ~~Changelog has been updated~~
- Are you fine with having the `typos` configuration in `./.typos.toml`? [Other path are possible and it is also possible to define a specific path as cli argument](https://github.com/crate-ci/typos/blob/master/docs/reference.md#sources)
- Do you want to add an additional `checkbox` in the `.github/pull_request_template.md`?
- I believe that `documentation` and `changelog` update do not apply to a `ci` change, but don't hesitate to correct me. I will then try to do the necessary updates
=> feat: typos checking in GitHub actions

src/ui/panes/lyrics.rs
=> fix: remove unneeded clone in lyrics

CHANGELOG.md, src/mpd/commands/outputs.rs, src/ui/modals/outputs.rs
completes #460
I'm having fun doing these tbh, it's like completing quests in a game :)
=> add plugin to outputs (finish #460)

CHANGELOG.md, src/core/command.rs, src/ui/browser.rs, src/ui/panes/playlists.rs, src/ui/panes/search.rs
Completes #428
I like watching the number on Pull Requests tab going down
=> correct ordering in Insert and InsertAll on multiple items (complete #428)

CHANGELOG.md, docs/src/content/docs/next/configuration/song-table.mdx, src/config/theme/properties.rs, src/ui/panes/mod.rs
https://github.com/mierak/rmpc/issues/463
=> feat: position property

CHANGELOG.md, src/ui/browser.rs, src/ui/panes/queue.rs, src/ui/panes/search.rs
https://github.com/mierak/rmpc/issues/473
=> feat: clear marked with close action

CHANGELOG.md, src/config/cli.rs, src/core/command.rs, src/mpd/mpd_client.rs, src/tests/fixtures/mpd_client.rs
https://github.com/mierak/rmpc/issues/506
=> feat: sendmessage cli

FAQ.md, docs/astro.config.mjs, docs/src/components/Header.astro, docs/src/pages/faq.astro
=> docs: move faq to header

CHANGELOG.md, src/config/cli.rs, src/core/command.rs
https://github.com/mierak/rmpc/issues/527
=> feat: queue cli

CHANGELOG.md, src/shared/mouse_event.rs, src/ui/browser.rs, src/ui/dirstack/dir.rs, src/ui/dirstack/state.rs, src/ui/modals/decoders.rs, src/ui/modals/info_list_modal.rs, src/ui/modals/keybinds.rs, src/ui/modals/outputs.rs, src/ui/modals/select_modal.rs, src/ui/panes/logs.rs, src/ui/panes/queue.rs, src/ui/panes/search.rs, src/ui/panes/tabs.rs, src/ui/widgets/browser.rs, src/ui/widgets/button.rs
Makes scrolling and scrollbars behave more naturally - similar to how web browsers handle them.
fixes #544
=> feat: better scrolling and scrollbars

CHANGELOG.md, docs/src/content/docs/next/configuration/index.mdx, src/config/defaults.rs, src/config/mod.rs, src/shared/lrc/lyrics.rs, src/shared/lrc/mod.rs, src/ui/panes/lyrics.rs
=> feat: global lrc offset

CHANGELOG.md, docs/src/content/docs/next/configuration/index.mdx, src/config/mod.rs, src/core/event_loop.rs
=> feat: run `on_song_change` at startup

src/config/keys/actions.rs, src/config/keys/mod.rs, src/config/mod.rs, src/config/tabs.rs, src/config/theme/queue_table.rs, src/core/event_loop.rs, src/core/input.rs, src/mpd/client.rs, src/mpd/commands/metadata_tag.rs, src/mpd/mpd_client.rs, src/shared/lrc/index.rs, src/ui/dir_or_song.rs, src/ui/image/ueberzug.rs, src/ui/mod.rs, src/ui/modals/input_modal.rs, src/ui/modals/keybinds.rs, src/ui/modals/menu/list_section.rs, src/ui/modals/select_modal.rs, src/ui/panes/albums.rs, src/ui/panes/directories.rs, src/ui/panes/lyrics.rs, src/ui/panes/mod.rs, src/ui/panes/playlists.rs, src/ui/panes/queue.rs, src/ui/panes/search.rs
Mainly collapse nested if let chains and resolve hidden lifetime ellision lint
=> chore: new clippy lints update

docs/astro.config.mjs
=> docs: fix copy button removing ron ext declarations

CHANGELOG.md, docs/src/content/docs/next/configuration/theme.mdx, src/config/mod.rs, src/core/event_loop.rs
=> fix: remote theme change

CHANGELOG.md, docs/src/content/docs/next/assets/example_config.ron, docs/src/content/docs/next/configuration/index.mdx, src/config/cli.rs, src/config/mod.rs, src/core/command.rs, src/shared/mpd_client_ext.rs, src/ui/mod.rs
=> feat: keep playback state on next/prev

CHANGELOG.md, docs/src/content/docs/next/assets/example_theme.ron, docs/src/content/docs/next/assets/themes/default/theme.ron, docs/src/content/docs/next/assets/themes/nord/theme.ron, docs/src/content/docs/release-0-9-0/assets/example_theme.ron, docs/src/content/docs/release-0-9-0/assets/themes/default/theme.ron, docs/src/content/docs/release-0-9-0/assets/themes/nord/theme.ron, src/config/theme/mod.rs, src/shared/ytdlp.rs
=> docs: remove mention of tab_bar.enabled

CHANGELOG.md, docs/src/content/docs/next/assets/example_config.ron, docs/src/content/docs/next/configuration/index.mdx, src/config/mod.rs, src/config/sort_mode.rs, src/shared/cmp.rs, src/shared/mod.rs, src/ui/dir_or_song.rs, src/ui/panes/albums.rs, src/ui/panes/mod.rs, src/ui/panes/playlists.rs, src/ui/panes/tag_browser.rs
fixes https://github.com/mierak/rmpc/issues/605
=> feat: ignore leading "the"

CHANGELOG.md, src/ui/panes/queue.rs
fixes https://github.com/mierak/rmpc/issues/624
=> feat: jumptocurrent in stopped state

CHANGELOG.md, src/core/event_loop.rs, src/ui/browser.rs, src/ui/dirstack/dir.rs, src/ui/dirstack/mod.rs, src/ui/dirstack/stack.rs, src/ui/mod.rs, src/ui/panes/albums.rs, src/ui/panes/directories.rs, src/ui/panes/playlists.rs, src/ui/panes/queue.rs, src/ui/panes/search/mod.rs, src/ui/panes/tag_browser.rs, src/ui/widgets/browser.rs
=> refactor: make queue share dir implementation
