mierak/rmpc

src/ui/screens/logs.rs, src/ui/screens/queue.rs, src/ui/widgets/kitty_image.rs
Fixes various edge cases (user is on a tab other than queue and changes current song) and avoids clone of the whole image on render
=> refactor: various improvements to async image

src/main.rs
fixes part of https://github.com/mierak/rmpc/issues/66
=> fix: always print CARGO_PKG_VERSION

docs/src/content/docs/installation.mdx
Now packaged in the official repositories: <https://archlinux.org/packages/extra/x86_64/rmpc/> 🥳
=> docs: update Arch Linux instructions

src/context.rs, src/main.rs, src/shared/ext.rs, src/shared/key_event.rs, src/shared/macros.rs, src/shared/mod.rs, src/tests/fixtures/mod.rs, src/ui/browser.rs, src/ui/mod.rs, src/ui/modals/add_to_playlist.rs, src/ui/modals/confirm_modal.rs, src/ui/modals/confirm_queue_clear.rs, src/ui/modals/keybinds.rs, src/ui/modals/mod.rs, src/ui/modals/outputs.rs, src/ui/modals/rename_playlist.rs, src/ui/modals/save_queue.rs, src/ui/modals/song_info.rs, src/ui/panes/album_art.rs, src/ui/panes/albums.rs, src/ui/panes/artists.rs, src/ui/panes/directories.rs, src/ui/panes/logs.rs, src/ui/panes/mod.rs, src/ui/panes/playlists.rs, src/ui/panes/playlists/tests.rs, src/ui/panes/queue.rs, src/ui/panes/search.rs, src/ui/tab_screen.rs
This completely removes internal key handler's result in order simplify the determination of whether render is wanted and event propagation.
=> refactor: simplify key event results

CHANGELOG.md, src/ui/modals/confirm_queue_clear.rs
This change improves the usability and clarity of the queue deletion confirmation modal.
- Renamed buttons from "Save" and "Cancel" to "Confirm" and "Cancel" for clarity
- Added support for TAB to cycle through 'Confirm' and 'Cancel' buttons
- Changed the Up and Down key for the Left and Right instead
- Updated the confirmation text to include a warning about the action being irreversible
- Removed unnecessary title for a cleaner UI
=> feat: enhance queue deletion confirm modal

CHANGELOG.md, src/mpd/client.rs, src/mpd/proto_client.rs, src/tests/fixtures/mpd_client.rs
Fixes issue where read buffer was not completely emptied after encountering error while reading MPD's response which resulted in spectacular borkedness of basically everything
=> fix: recreate read stream on error

CHANGELOG.md, src/ui/modals/confirm_playlist_delete.rs, src/ui/modals/mod.rs, src/ui/panes/playlists.rs
Similar to the queue list deletion behavior, a playlist can contain a **lot** of songs; hence, the confirmation modal. 
This prevents users like me to fat-fingering this action and delete its beloved playlist ;)
=> feat: add confirmation modal for playlist deletion

CHANGELOG.md, docs/src/content/docs/configuration/index.mdx, docs/src/content/docs/configuration/lyrics.mdx, src/cli.rs, src/config/cli.rs, src/config/mod.rs, src/config/tabs.rs, src/context.rs, src/main.rs, src/shared/lrc.rs, src/shared/lrc/index.rs, src/shared/lrc/lyrics.rs, src/shared/lrc/mod.rs, src/shared/mod.rs, src/tests/fixtures/mod.rs, src/ui/mod.rs, src/ui/panes/lyrics.rs, src/ui/panes/mod.rs, src/ui/tab_screen.rs
For now its just a simple unfocusable pane like `AlbumArt`
<details>
<summary>Quick preview</summary>
</details>
=> [WIP] feat: time synced lyrics pane

CHANGELOG.md, src/ui/widgets/browser.rs
In browser panes, the scrollbar position overlaps the pane separator.
This fits nicely with defaults symbols.
However, for a more minimalist approach with empty symbols, eg.
`scrollbar: (symbols: ["", "│", "", ""])`, the scrollbar becomes
invisible or bearly visible depending on the chosen character.
Assume that if the `track` symbol is empty, we expect the scrollbar
to be visible but not overlap with the pane separator.
Solution: Shift the horizontal position to the left.
This ensures the scrollbar remains visible and properly positioned
in all cases, matching the queue appareance.
=> fix: adjust scrollbar position in browser panes

src/ui/widgets/browser.rs
The position need to be adjusted as well when `draw_borders` is false.
=> fixup: handle scrollbar position when no border

CHANGELOG.md, src/context.rs, src/core/event_loop.rs, src/main.rs, src/shared/events.rs, src/shared/ext.rs, src/shared/macros.rs, src/shared/tmux.rs, src/ui/image/facade.rs, src/ui/image/iterm2.rs, src/ui/image/kitty.rs, src/ui/image/mod.rs, src/ui/image/sixel.rs, src/ui/image/ueberzug.rs, src/ui/mod.rs, src/ui/panes/album_art.rs, src/ui/panes/albums.rs, src/ui/panes/artists.rs, src/ui/panes/directories.rs, src/ui/panes/logs.rs, src/ui/panes/lyrics.rs, src/ui/panes/mod.rs, src/ui/panes/playlists.rs, src/ui/panes/queue.rs, src/ui/panes/search.rs, src/ui/tab_screen.rs, src/ui/widgets/browser.rs
This greatly simplifies and unifies the code around the different image protocol backends and gets it to a place where I am generally happy with it. I was able to remove a bunch of hacks and improper solutions while also allowing better handling of resize events, simplifying the program flow and other things.
One unfortunate side effect is that Kitty's image is no longer centered anymore and is instead rendered in the top left corner, but this at least brings it in line with the other backends and I plan to introduce image alignment config at some point this release anyway.
Anyway, this is not 100% ready yet but is almost there. Its mostly testing whether something is broken thats left, so if you stumble upon this before merge and feel like testing it out, feel free to do so, thanks!
=> refactor: image protocols

CHANGELOG.md, src/mpd/commands/lsinfo.rs, src/ui/panes/directories.rs, src/ui/panes/mod.rs
This properly supports the `playlist` entry in `lsinfo` MPD protocol command. The `playlist` as a key was ignored untill now because that behaviour is deprecated by mpd. The ignore was however done incorrectly and could result in incorrect parsing of MPD's response and sometimes even fail altogether.
=> fix: lsinfo not supporting playlists

CHANGELOG.md, docs/src/content/docs/next/assets/example_config.ron, docs/src/content/docs/next/configuration/album-art.mdx, docs/src/pages/changelog.astro, src/config/album_art.rs, src/config/mod.rs, src/context.rs, src/shared/image.rs, src/ui/image/facade.rs, src/ui/image/iterm2.rs, src/ui/image/kitty.rs, src/ui/image/sixel.rs, src/ui/panes/album_art.rs
This will allow us to align album art in its provided area if it does not fill it completely. Till now kitty was centered and others were rendered in the top left column.
Some work left to do, kitty, iterm2 and sixel ~~are now aligned to center,~~ can configure vertical and horizontal alignment separately, ueberzug is untouched still.
=> feat: album art alignment

docs/src/content/docs/next/configuration/header.mdx, docs/src/content/docs/release/configuration/header.mdx
fixes https://github.com/mierak/rmpc/issues/201
=> docs: fix status property

src/ui/mod.rs, src/ui/panes/album_art.rs, src/ui/panes/albums.rs, src/ui/panes/artists.rs, src/ui/panes/directories.rs, src/ui/panes/mod.rs, src/ui/panes/playlists.rs, src/ui/panes/playlists/tests.rs, src/ui/panes/queue.rs, src/ui/panes/search.rs
fixes album art showing after closing modal on a tab which does not containt an album art also fixes album art showing on other tab if user switches tabs before the image download finishes
fixes https://github.com/mierak/rmpc/issues/206
=> fix: album art showing when its not supposed to

CHANGELOG.md, src/mpd/errors.rs, src/mpd/mpd_client.rs
addresses issues found in https://github.com/mierak/rmpc/issues/212
=> fix: properly escape strings on proto level

src/mpd/mpd_client.rs, src/mpd/proto_client.rs
Addresses `No such song` error found in https://github.com/mierak/rmpc/issues/212.
Basically with MPD command list, whenever an error is encountered the whole command list stops processing. This PR allows rmpc to continue where it left off by submitting another command list. The song which failed simply gets no stickers and a warning is logged.
=> fix: reading stickers in queue for songs outside the music database

CHANGELOG.md, src/core/event_loop.rs, src/core/scheduler/mod.rs, src/shared/mpd_query.rs, src/ui/browser.rs, src/ui/panes/lyrics.rs
With the newly introduced scheduler, it is now possible to trigger lyrics update precisely when they are supposed to be displayed. Previously they were refreshed periodically with interval set by `status_update_interval_ms` only which could result in small delays between lrc line switching.
=> feat: schedule precise render fiming for lyrics

src/ui/panes/mod.rs
When filtering the queue list, capital letters were not accounted for,
leading to no result. With this change, users can now filter without
worrying about exact capitalization.
=> fix: case-insentive comparison in Property matching

CHANGELOG.md, src/ui/panes/album_art.rs
Problem:
- Album art rerendering could overlap open modals, making content unreadable
- This occurred with events like `UiEvent::SongChanged`, `UiEvent::Reconnected`,
and `AppEvent::Resized` while a modal was open on the queue list
Solution:
- Add an `is_modal_open` flag to AppContext to track modal state
- Implement checks to prevent album art rendering when a modal is open
- Defer album art updates until modal is closed
=> fix: prevent album art rendering when modal is open

CHANGELOG.md, docs/src/content/docs/next/assets/example_config.ron, docs/src/content/docs/next/configuration/tabs.mdx, src/config/mod.rs, src/config/tabs.rs, src/config/theme/mod.rs, src/config/theme/properties.rs, src/config/theme/style.rs, src/ui/mod.rs, src/ui/panes/mod.rs, src/ui/tab_screen.rs
This PR deprecates the `border_type` property on tabs, it will be silently ignored. Instead you can now configure the borders per Pane/Split which allows you to replicate the former behavior while providing more control over them at the same time.
The borders are specified as `borders: "<value>"` where value can be `NONE`, `ALL`, `RIGHT`, `LEFT`, `TOP`, `BOTTOM`, their combination, ie. `borders: "RIGHT | LEFT"` or omitted altogether which implies `NONE`.
Note that you now have to account for the borders if you use exact sizing of panes. For example if your `Header` is supposed to be 2 rows tall and has borders at `TOP` and `BOTTOM` you must set its size as `4` as seen in the example below.
Consider this layout:  
<details>
<summary>Click to expand</summary>
```rust
layout: Split( …
```
=> [WIP] feat: better borders in tabs/layout

src/config/theme/header.rs, src/config/theme/properties.rs, src/config/theme/style.rs, src/ui/panes/mod.rs
Inspired by: https://github.com/mierak/rmpc/issues/233#issuecomment-2634044814
Simplifies the provided configuration to not require two properties: 
```rust
(kind: Property(Status(RandomV2(
on_label: " ",
off_label: " ",
on_style: (fg: "#5ea1ff", modifiers: "Bold"),
off_style: (fg: "#5ea1ff", modifiers: "Dim"),
)))),
(kind: Property(Status(RepeatV2(
on_label: " ",
off_label: " ",
on_style: (fg: "#5ea1ff", modifiers: "Bold"),
off_style: (fg: "#5ea1ff", modifiers: "Dim"),
)))),
```
=> feat: configurable styles for new per state properties

CHANGELOG.md, Cargo.toml, docs/src/content/docs/next/assets/example_theme.ron, docs/src/content/docs/next/assets/themes/catppuccin-macchiato/theme.ron, docs/src/content/docs/next/configuration/theme.mdx, src/config/theme/mod.rs, src/ui/mod.rs
This change enhances the UI by optionally dimming the background when
modals are displayed, improving focus and user experience.
An opt-in setting `modal_backdrop` is introduced in the theme
configuration to enable or disable (default) modal backdrops.
=> feat(ui): add backdrop support for modals

CHANGELOG.md, Cargo.lock, Cargo.toml, docs/src/content/docs/next/assets/example_config.ron, docs/src/content/docs/next/configuration/index.mdx, src/config/mod.rs, src/core/config_watcher.rs, src/core/event_loop.rs, src/core/mod.rs, src/main.rs, src/shared/events.rs, src/ui/image/facade.rs, src/ui/image/iterm2.rs, src/ui/image/kitty.rs, src/ui/image/sixel.rs, src/ui/mod.rs, src/ui/panes/album_art.rs, src/ui/panes/queue.rs, src/ui/panes/search.rs, src/ui/panes/tabs.rs, src/ui/tab_screen.rs, src/ui/widgets/tabs.rs
Makes rmpc watch config file for changes and reload them automatically. Some config values are cont reloadable, mainly the album art backend and stuff dealing with mpd connection etc. These still need full restart. Still needs a little bit of work before merging, but its working well.
Fixes https://github.com/mierak/rmpc/issues/168
=> feat: config hot reload

CHANGELOG.md, src/config/cli.rs, src/config/mod.rs, src/core/config_watcher.rs, src/main.rs, src/shared/ipc/commands/set.rs, src/tests/fixtures/mod.rs
@soifou Is it alright like this? It requires an absolute path to the theme, ie `~/.config/rmpc/themes/theme.ron`.
Changing it to be able to just use a theme name is possible but complicates it a bit because we have to check whether we even have config file etc.
edit: this way it is also consistent with the way the IPC theme command is done
=> feat: theme cli arg

src/ui/panes/album_art.rs
Test cases per different album art backend are not needed anymore since that functionality has been abstracted away from the pane itself
=> chore: drop unneeded test cases

CHANGELOG.md, src/ui/panes/lyrics.rs
Before, the first lyrics would be highlighted even before it's own timestamp was reached
=> feat(lyrics): don't highlight until the first lyrics have been reached

CHANGELOG.md, src/shared/lrc/lyrics.rs
Ik that it's not mentioned on the Wikipedia page (prob since LRC isn't really standardised), but some lyric providers (Netease and Apple Music for example) use 3s.f. for the fraction part of a second, causing the most significant digit to be treated as a second. This fixes the issue, by letting any number of s.f. to be used.
=> fix(lyrics): parse lyric timestamps with frations of seconds which aren't to 2s.f.

docs/src/content/docs/next/configuration/keybinds.mdx
In emacs `Alt` is called `Meta`. I also mentioned that in order to make searching for `meta` possible.
=> Update documentation to mention `Alt` key`

CHANGELOG.md, docs/src/content/docs/next/configuration/tabs.mdx, src/config/mod.rs, src/config/tabs.rs, src/context.rs, src/mpd/mpd_client.rs, src/shared/events.rs, src/shared/mod.rs, src/shared/mpd_query.rs, src/shared/string_util.rs, src/tests/fixtures/mpd_client.rs, src/ui/mod.rs, src/ui/panes/album_art.rs, src/ui/panes/albums.rs, src/ui/panes/artists.rs, src/ui/panes/directories.rs, src/ui/panes/mod.rs, src/ui/panes/playlists.rs, src/ui/panes/queue.rs, src/ui/panes/search.rs, src/ui/panes/tag_browser.rs, src/ui/tab_screen.rs
fixes https://github.com/mierak/rmpc/issues/265
This essentially converts the current `Artists`/`AlbumArtists` pane to a more generic one where you can define what tag is used for the first/root level of the browser. There is also an optional separator which lets you use tags containing a delimiter separated values as discrete entries in the browser's root level.
This is similar but a more powerful version of ncmpcpp's `media_library_primary_tag`
Usage:
```ron
(
name: "Genre",
border_type: None,
pane: Pane(Browser(root_tag: "genre", separator: ";")),
),
```
Which means the `genere` tag value gets split by `;` and each value gets its separate entry in the browser.
`Artists` and `AlbumArtists` panes stay backwards compatible but are now internally represented as `Pane(Browser(root_tag: …
=> feat: new browser pane with configurable root tag

CHANGELOG.md, Cargo.lock, Cargo.toml, docs/src/content/docs/next/configuration/tabs.mdx, src/config/tabs.rs, src/mpd/commands/status.rs, src/ui/panes/mod.rs, src/ui/panes/property.rs, src/ui/widgets/mod.rs, src/ui/widgets/scrolling_line.rs
fixes https://github.com/mierak/rmpc/issues/226
Makes property panes cycle around when they do not fit their area.
Example:
```ron
(
size: "60%",
pane: Pane(Property(
content: [
(kind: Property(Song(Artist)), default: (kind: Text("Unknown"))),
(kind: Text(" - ")),
(kind: Property(Song(Album)), default: (kind: Text("Unknown Album")))
], align: Center, scroll_speed: 2
)),
),
```
Makes the content of this property cycle by 2 columns each second(tied to the elapsed time of the currently playing song, so it wont cycle when paused). Not specifying `scroll_speed` or setting it to 0 disables this.
=> feat: cycling/scrolling property pane

CHANGELOG.md, docs/src/content/docs/next/configuration/song-table.mdx, src/config/theme/properties.rs, src/ui/panes/mod.rs
Removes extension from the `Filename` property and introduces a new `FileExtension` property instead.
=> feat: add FileExtension property

.vscode/settings.json, src/mpd/commands/status.rs, src/mpd/mod.rs, src/shared/mpd_query.rs
Fixes terminal getting spammed with warnings that this key/value pair of `lastloadedplaylist` not being handled:
```
2025-03-31T08:09:45.862124626Z WARN  thread=request src/mpd/mod.rs:21 message="Encountered unknow key/value pair" key="lastloadedplaylist" value=""
```
I understand it's not being used at the moment, so if we want to we could probably just set this to `None` as well, let me know what you think.
Last loaded playlist is a string, which can be seen in [mpd's src/queue/Queue.hxx, tag v0.24.2](https://github.com/MusicPlayerDaemon/MPD/blob/v0.24.2/src/queue/Queue.hxx#L89).
Also went ahead and fixed that typo which existed [here](https://github.com/mierak/rmpc/blob/d5ec479eef0cb34df7b1d7ee5e5d034b7a33aca3/src/mpd/mod.rs#L21) for `FromMpd::next`, `LineHandled::No` case.
=> Handle new value lastloadedplaylist from mpd

CHANGELOG.md, Cargo.lock, Cargo.toml, src/config/mod.rs, src/core/config_watcher.rs, src/core/event_loop.rs, src/main.rs, src/shared/events.rs, src/shared/macros.rs, src/ui/mod.rs, src/ui/modals/confirm_modal.rs, src/ui/modals/info_modal.rs, src/ui/modals/mod.rs, src/ui/panes/album_art.rs, src/ui/panes/playlists.rs, src/ui/panes/queue.rs
This adds a modal popup which shows a better description of where the error occurred when reading an invalid config file
=> feat: better errors when reading config

CHANGELOG.md, docs/src/content/docs/next/assets/example_theme.ron, docs/src/content/docs/next/assets/themes/default/theme.ron, docs/src/content/docs/next/configuration/theme.mdx, src/config/defaults.rs, src/config/theme/mod.rs, src/core/event_loop.rs, src/mpd/commands/current_song.rs, src/mpd/commands/metadata_tag.rs, src/mpd/commands/mod.rs, src/shared/lrc/index.rs, src/tests/fixtures/mpd_client.rs, src/ui/dirstack/mod.rs, src/ui/modals/song_info.rs, src/ui/panes/directories.rs, src/ui/panes/mod.rs, src/ui/panes/playlists.rs, src/ui/panes/property.rs, src/ui/panes/queue.rs, src/ui/panes/tag_browser.rs, src/ui/widgets/header.rs
fixes #303
This adds support for multiple values in a single tag. In the formatters they get joined by the new `format_tag_separator` and in the tag lists (info modal, browsers) they simply get listed multiple times for each value.
=> feat: support multiple tag values

CHANGELOG.md, src/ui/panes/lyrics.rs
When displaying long lyrics line, current implementation will truncate the line if it‘s longer than the pane width. (as shown below).
With this PR, the long lyrics line will be wrapped.
=> feat(lyrics): Implement word wrapping for lyrics pane.

CHANGELOG.md, Cargo.toml, build.rs, docs/src/content/docs/next/configuration/keybinds.mdx, src/config/cli.rs, src/config/keys/actions.rs, src/core/command.rs, src/mpd/mod.rs, src/mpd/mpd_client.rs, src/mpd/queue_position.rs, src/tests/fixtures/mpd_client.rs, src/ui/browser.rs, src/ui/modals/add_random_modal.rs, src/ui/panes/albums.rs, src/ui/panes/directories.rs, src/ui/panes/playlists.rs, src/ui/panes/queue.rs, src/ui/panes/search.rs, src/ui/panes/tag_browser.rs
The added Insert and InsertAll commands allow adding songs directly after the current song, with mpd's POSITION argument on its API.
This just changes what it needs to, it was done by adding the command and then being taken by the hand by the compiler and adding the explicit matches everywhere they were needed. Basic testing was done.
Since I don't know exactly how the queue view works, I didn't implement its Insert action, even though it would be interesting, since it is often needed to add a song already in the queue directly after the current track. Note it is still possible to do so manually by simply moving the track up. An implementation of this would probably add the song a second time instead of moving it.
=> feat: Add Insert and InsertAll commands

CHANGELOG.md, src/config/cli.rs, src/core/command.rs, src/main.rs, src/mpd/client.rs, src/mpd/mpd_client.rs, src/tests/fixtures/mpd_client.rs
this introduces `listpartitions` command and `--partition` + `--autocreate` arguments to the CLI which allows you to connect to a specified MPD partition
they should work for both the tui and CLI
=> feat: initial partition support

CHANGELOG.md, src/shared/lrc/index.rs
I've noticed that titles that include a closing bracket (like "some song title [Explicit]") didn't get indexed.
During debugging this, I found that the artist metadata field is passed twice to the find_lrc function.
This PR fixes this.
I had some more issues trying to get my .lrc files to be read/matched, though they might be too specific/uncommon to bother fixing:
- Files that start with [BOMs](https://de.wikipedia.org/wiki/Byte_Order_Mark) fail to be parsed
- Length mismatches, which made me wonder if matching the length is truly nessesary
- Some .lrc files missing an album metadata field, resulting in them not getting indexed
=> Fix: Lyrics files with ']' in the metadata fields not getting indexed and title not getting matched

CHANGELOG.md, docs/src/content/docs/next/configuration/lyrics.mdx, src/shared/lrc/index.rs
This makes lrc matching more lenient. Matching is now case insensitive and album is only considered if both the song and the lrc file contain album metadata, but if multiple matches are found, the matches with album are prioritized.
Length is now only considered with multiple matches:
* First try to find lrc that is +- 5 seconds
* If not found check whether any lrc file without length was found
* as a last resort, return the closest match by length
There is a bunch of tests which should hopefully describe the behavior in more detail.
@Lxtharia I am looking for a feedback since you were interested in this. What do you think about this behavior?
Note: I am merging this to get it off my head, but please do leave a feedback if you have any.
https://github.com/mierak/rmpc/issues/391 …
=> feat: make lyrics matching more lenient

.github/ISSUE_TEMPLATE/bug.yml, CHANGELOG.md, CONTRIBUTING.md, src/shared/logging.rs
- The logs are now stored in  `/tmp/rmpc_${UID}.log`  rather than  `/tmp/rmpc.log` , which will not cause any permission issues as each user will have the file with their own UID
- Closes #414
=> Changed logging path and fixed multiple user using rmpc issue

CHANGELOG.md, docs/src/content/docs/next/assets/example_theme.ron, docs/src/content/docs/next/configuration/theme.mdx, src/config/theme/lyrics.rs, src/config/theme/mod.rs, src/ui/panes/lyrics.rs
adds lyrics.show_timestamp to add the timestamp of each line
it ignores empty lines
=> Add lyrics config option to show line timestamps

src/mpd/mpd_client.rs, src/tests/fixtures/mpd_client.rs, src/ui/panes/playlists.rs
There has been no release since the Insert feature was added, making updating `CHANGELOG.md` superfluous.
=> fix: Actually insert and not add playlists when using Insert

CHANGELOG.md, src/ui/panes/playlists.rs
=> fix: allow playlists with no preview

CHANGELOG.md, docs/src/content/docs/next/configuration/cava.mdx, docs/src/content/docs/next/configuration/index.mdx, docs/src/content/docs/next/configuration/layout.mdx, docs/src/content/docs/next/configuration/theme.mdx, src/config/theme/mod.rs, src/config/theme/properties.rs, src/core/event_loop.rs, src/core/scheduler/mod.rs, src/core/socket.rs, src/mpd/mpd_client.rs, src/mpd/proto_client.rs, src/shared/ext.rs, src/shared/image.rs, src/shared/ipc/commands/set.rs, src/shared/lrc/index.rs, src/shared/mouse_event.rs, src/ui/dirstack/mod.rs, src/ui/dirstack/state.rs, src/ui/image/kitty.rs, src/ui/image/ueberzug.rs, src/ui/panes/property.rs, src/ui/panes/queue.rs, src/ui/widgets/header.rs, src/ui/widgets/input.rs, src/ui/widgets/scan_status.rs
Here is a `pull request` addressing the typos noted in #450 as well as other misspelling
_note:_ I will keep this `pull request` in `Draft` until I have addressed all typos I can find
#450
this `pull request` is fixing typos found in the changelog and configuration options name
which means breaking change for people already using those options
this is a necessary fix to avoid more affected users once the typos are present in a versioned release
If you wish to delay or edit this `pull request`, feel free to do so. And please let me know why so I can help further.
=> fix: typos

CHANGELOG.md, docs/src/content/docs/next/assets/example_config.ron, docs/src/content/docs/next/assets/example_theme.ron, docs/src/content/docs/next/assets/themes/catppuccin-macchiato/theme.ron, docs/src/content/docs/next/assets/themes/default/theme.ron, docs/src/content/docs/next/assets/themes/nord/theme.ron, docs/src/content/docs/next/configuration/index.mdx, docs/src/content/docs/next/themes/nord.mdx, src/config/defaults.rs, src/config/mod.rs, src/config/sort_mode.rs, src/config/theme/mod.rs, src/core/command.rs, src/mpd/commands/lsinfo.rs, src/mpd/queue_position.rs, src/ui/dir_or_song.rs, src/ui/dirstack/mod.rs, src/ui/panes/directories.rs, src/ui/panes/playlists.rs, src/ui/panes/playlists/tests.rs, src/ui/panes/search.rs
Introduces support for playlists in the directories pane. A new option to control the behavior
is also created.
Note: `group_directories_first` on `directories_sort` was changed to `group_by_type`. This is a
small breaking change in case you were on the git version.
https://github.com/mierak/rmpc/issues/433
=> feat: support playlists in directories pane

CONTRIBUTING.md, README.md
Small `pull request` removing trailing whitespaces from the `repo`
_none_
=> chore: removing trailing whitespace in `markdown` files

CHANGELOG.md, src/shared/ytdlp.rs
Using a [youtu.be url](https://www.youtu.be/dQw4w9WgXcQ) returns an error because the URL wasn't supported, this pull request fixes that (I guess)
Thanks for this AMAZING mpd client btw!
None that I noticed
=> Add youtu.be url support for addyt

docs/src/content/docs/next/configuration/cava.mdx, src/config/theme/cava.rs, src/ui/panes/cava.rs
```ron
orientation: Horizontal
```
```ron
orientation: Top
```
=> feat: cava orientation config

docs/src/content/docs/next/configuration/cava.mdx, src/config/defaults.rs, src/config/theme/cava.rs, src/core/event_loop.rs, src/ui/image/mod.rs, src/ui/panes/cava.rs
Fixes handling of cavas background color. It should now render the background color in cava's pane
at all times and also render inbetween the columns.
Also fixes fallback to rmpc's background color if cava's color was not defined.
Additionally, `inverted_bar_symbols` were added to config to be used for the bottom part of the
rendering when using orientation `Horizontal` or `Top` instead of simply inverting colors on the
normal `bar_symbols`. This should match cava's behavior.
And also fixed a small issue introduced recently with cava where rmpc would not issue a rerender
right away after a resize occured.
https://github.com/mierak/rmpc/issues/482
=> fix: cava bg color and add inverted symbols

src/shared/ext.rs
This is causing rmpc 0.9.0 to fail to compile on Alpine's 32-bit architectures (x86, armv7, armhf). I will probably just add a patch in aports for now so that you don't need to make a new release just for this.
- not sure if this is really relevant
=> fix: use 32 bit usize constants in tests

src/mpd/client.rs, src/mpd/mpd_client.rs, src/mpd/proto_client.rs, src/tests/fixtures/mpd_client.rs
Splits MPD client in two parts, one sends the commands, the second reads correct response for the
given command. This was a long time coming to better support MPD's command lists.
There should be no beavior changes.
First part of 2(?). The ProtoClient needs to go next.
=> refactor: split MPD client in sending/reading parts

docs/src/content/docs/next/configuration/cava.mdx, docs/src/content/docs/next/configuration/keybinds.mdx, docs/src/content/docs/release-0-9-0/configuration/cava.mdx
Browsing the keybinding and cava page to configure rmpc and finding some typos.
I only fixed the next release docs, tell me if you want me to also change the current release docs
=> docs: fix typos

CHANGELOG.md, docs/src/content/docs/next/configuration/lyrics.mdx, src/shared/lrc/index.rs, src/shared/lrc/lyrics.rs, src/shared/lrc/mod.rs
This PR introduces a significant change in how the LRC parser handles errors and bracketed text inside lyrics.
**Key changes:**
* I made the parser more forgiving by having it skip over malformed lines, invalid timestamps, or bad metadata instead of failing or crashing. Since real-world `.lrc` files can be messy or inconsistent, I believe it’s better to show partial lyrics than none at all for a better ux, plus how its mentioned in the issue itself.
* I also fixed how the parser handles brackets inside lyrics. Previously, bracketed text like `[Drum Solo]` was mistakenly treated as metadata tags, causing those parts to be lost or leading to parsing failures. Now, the parser correctly distinguishes between actual tags (timestamps and metadata) and brackets that are part of the lyrics, and …
=> feat/improve LRC parsing logic

CHANGELOG.md, docs/src/content/docs/next/configuration/keybinds.mdx, src/config/keys/key.rs, src/config/keys/mod.rs, src/main.rs, src/shared/key_event.rs, src/shared/terminal.rs
Adds support for [kitty's keyboard protocol](https://sw.kovidgoyal.net/kitty/keyboard-protocol/).
This allows for more keybind combinations in supported terminals, for example combining CTRL and SHIFT on one keybind.
Hopefully this does not break anything. Unfortunatelly no support in tmux, its blocked upstream.
=> feat: support kitty keyboard protocol

Cargo.toml, src/config/theme/cava.rs, src/config/theme/queue_table.rs, src/shared/geometry.rs, src/shared/image.rs, src/shared/mouse_event.rs, src/tests/fixtures/mpd_client.rs, src/ui/image/block.rs, src/ui/image/ueberzug.rs, src/ui/modals/decoders.rs, src/ui/modals/info_list_modal.rs, src/ui/modals/keybinds.rs, src/ui/modals/menu/list_section.rs, src/ui/modals/menu/modal.rs, src/ui/modals/menu/multi_action_section.rs, src/ui/panes/cava.rs, src/ui/panes/search.rs, src/ui/panes/volume.rs, src/ui/widgets/mod.rs
=> chore: rust 1.88, disable clippy cast lints

CHANGELOG.md, Cargo.toml, docs/src/content/docs/next/guides/remote-commands.mdx, docs/src/content/docs/next/reference/cli-command-mode.mdx, src/config/cli.rs, src/core/event_loop.rs, src/core/socket.rs, src/main.rs, src/shared/events.rs, src/shared/exit_code.rs, src/shared/ipc/commands/index_lrc.rs, src/shared/ipc/commands/keybind.rs, src/shared/ipc/commands/mod.rs, src/shared/ipc/commands/query_tab.rs, src/shared/ipc/commands/set.rs, src/shared/ipc/commands/status_message.rs, src/shared/ipc/commands/switch_tab.rs, src/shared/ipc/in_flight_ipc.rs, src/shared/ipc/ipc_stream.rs, src/shared/ipc/mod.rs, src/shared/mod.rs, src/shared/string_util.rs, src/tests/fixtures/mod.rs, src/tests/remote_ipc.rs, src/ui/browser.rs
Work in progress.
Adds a query command, currently allows to query only the active tab, allows to query multiple things
at once for any future extensibility. `rmpc remote query [TARGETS..]`
The whole IPC mechanism is now more robust with standardized way to propagate errors and response messages all the way up to the client side rmpc with very little space for possible mistakes during implementation of new ipc commands. One more pass on the already existing remote commands should be done in a separate PR to use the new functionality though.
Currently responds in format `key: value` (subject to change), ie.
```
active-tab: Queue
some-other-key: Value
...
```
finishes https://github.com/mierak/rmpc/issues/499
=> feat: ipc query command

CHANGELOG.md, docs/src/content/docs/next/assets/example_config.ron, docs/src/content/docs/next/configuration/index.mdx, src/config/artists.rs, src/ui/panes/tag_browser.rs
Allow album artists + artist + genre panes to support configurable date tags with fallback behavior.
In my `config.ron` to use this I have:
```
artists: (
album_display_mode: SplitByDate,
album_sort_by: Date,
album_date_tags: [OriginalDate, Date], // changed during PR to not be strings
),
```
https://github.com/mierak/rmpc/issues/568
=> support originaldate tag when browsing

CHANGELOG.md, src/ui/panes/tag_browser.rs
Adding synthesised albums when using split by date was adding all songs from the given album and not just the subset of entries for the given date.
fixes #580
=> fix: adding non-album entries with split by date adding more than intended

CHANGELOG.md, docs/src/content/docs/next/configuration/index.mdx, docs/src/content/docs/next/configuration/theme.mdx, src/config/mod.rs
Hi! I made a small feature pr for allowing user to specify a relative path to a theme.ron file.
Can't specify absolute/relative theme path in config file with file extension. Only a theme name with hard coded directory 'themes' are allowed.
=> feat: Added an ability to specify relative/absolute theme path in config

CHANGELOG.md, docs/src/content/docs/next/guides/youtube.mdx, src/config/cli.rs, src/core/command.rs, src/shared/ytdlp.rs, src/ui/mod.rs
- Introduces --name to addyt to resolve the first YouTube match and enqueue via existing download pipeline.
- Works in CLI and TUI Command Mode (custom argv splitter, no extra deps).
=> Add addyt --name to search by song title

CHANGELOG.md, src/shared/ytdlp.rs
Change the code which handles searching inside the yt-dlp cache directory to hopefully better handle
platforms other than linux.
https://github.com/mierak/rmpc/issues/591
=> fix: attempt fix of yt-dlp cache on non-linux

CHANGELOG.md, docs/src/content/docs/next/configuration/keybinds.mdx, docs/src/content/docs/next/configuration/stickers.mdx, src/config/keys/actions.rs, src/ctx.rs, src/ui/browser.rs, src/ui/mod.rs, src/ui/modals/menu/mod.rs, src/ui/panes/queue.rs, src/ui/panes/search/inputs.rs, src/ui/panes/search/mod.rs
Builds on top of #633 and adds a like functionality. Liked songs are represented with the "like"
sticker where possible values are 0, 1 and 2 which mean "disliked", "neutral" and "liked" respectively.
This is to be consistent with basically the only thing even remotely representing standards for
sticker between MPD clients https://github.com/jcorporation/mpd-stickers and because it generally
makes sense.
fixes #484
=> feat: like/dislike functionality

CHANGELOG.md, Cargo.toml, src/ctx.rs, src/shared/mpd_query.rs, src/ui/browser.rs, src/ui/dirstack/mod.rs, src/ui/dirstack/path.rs, src/ui/dirstack/stack.rs, src/ui/panes/albums.rs, src/ui/panes/directories.rs, src/ui/panes/playlists.rs, src/ui/panes/playlists/tests.rs, src/ui/panes/tag_browser.rs, src/ui/widgets/browser.rs
No changes to behavior (hopefully) except fewer refetches and more caching in rmpc. This further
simplifies the data flow in the various browsers and brings their implementation closer to each other.
Also makes rmpc keep the dir state when going back out.
Also fixes https://github.com/mierak/rmpc/issues/658
=> refactor: dirstack to tree structure
